name: deploy

on:
  push:
    branches:
      #      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-docker-cache-${{ github.sha }}
          restore-keys: ${{ runner.os }}-docker-cache-
          path: ./.docker-cache


      - name: Stop Docker daemon
        run: |
          sudo systemctl stop docker
          sudo systemctl stop docker.socket

      - name: Configure Docker daemon
        run: |
          sudo tee /etc/docker/daemon.json > /dev/null <<EOF
          {
            "data-root": "${{ github.workspace }}/.docker-cache
          }
          EOF

      - name: Start Docker with new root
        run: |
          sudo systemctl start docker
          sleep 5

      - run: |
          echo 1
          docker info
          echo 2
          docker images
          echo 3

#          docker image

      #      - uses: docker/setup-buildx-action@v3


      #      - uses: docker/bake-action@v5
      #        with:
      ##          load: true
      #          set: |
      #            *.cache-from=type=local,src=/tmp/.docker-cache
      #            *.cache-to=type=local,dest=/tmp/.docker-cache-new,mode=max

      #      - run: docker compose up test

#      - run: docker compose build test
#      - run: |
#          rm -rf /tmp/.docker-cache
#          mv /tmp/.docker-cache-new /tmp/.docker-cache

