name: deploy

on:
  push:
    branches:
      #      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        id: cache
        with:
          key: ${{ runner.os }}-docker-cache-${{ github.sha }}
          restore-keys: ${{ runner.os }}-docker-cache-
          path: ./docker.tar

      - run: echo "${{ steps.cache.outputs.cache-hit }}"
      - run: echo "${{ steps.cache.outputs.cache-matched-key }}"
#      - name: restore docker
#        if: steps.cache.outputs.cache-matched-key != ''
#        run: |
#          sudo systemctl stop docker
#          sudo tar -xf ./docker.tar
#          sudo rm -rf /var/lib/docker
#          sudo mv var/lib/docker /var/lib/docker
#          sudo systemctl start docker

      - run: |
          docker compose up -d test-db --wait
          docker images

      - name: generate docker cache
        run: |
          sudo systemctl stop docker docker.socket
          sudo tar -cf ./docker.tar /var/lib/docker

