name: deploy

on:
  push:
    branches:
      #      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/bake-action@v5
        with:
          push: false
          load: true
          set: |
            *.cache-to=type=gha,mode=max
            *.cache-from=type=gha
      - run: docker compose up test




