name: deploy

on:
  push:
    branches:
      - main

      #      test
      - develop

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - run: docker compose -v
