name: deploy

on:
  push:
    branches:
      #      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Stop Docker processes
        run: |
          sudo kill $(pidof dockerd) || true
          sudo kill $(pidof containerd) || true
          sleep 2

      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-docker-cache-${{ github.sha }}
          restore-keys: ${{ runner.os }}-docker-cache-
          path: ./docker.tar

      - run: tar -xf ./docker.tar
      - run: ls
      - run: ls docker

      - name: Start Docker daemon
        run: |
          sudo containerd &
          sleep 2
          sudo dockerd --debug &
          sleep 2

      - run: docker compose up -d test-db --wait

      - run: |
          docker images

      - name: Stop Docker processes
        run: |
          sudo kill $(pidof dockerd) || true
          sudo kill $(pidof containerd) || true
          sleep 2

      - run: sudo chmod -R 777 /var/lib/docker
      - run: sudo tar -cf ./docker.tar /var/lib/docker
      - run: ls
#      - run: sudo tar -zxvf aaa.tar.gz
