name: deploy

on:
  push:
    branches:
      #      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

#      - uses: actions/cache@v4
#        with:
#          key: ${{ runner.os }}-buildx-cache
#          path: /tmp/.buildx-cache

      - uses: docker/setup-buildx-action@v3
      - uses: docker/bake-action@v5
        with:
          load: true
          set: |
            *.output=type=local,dest=/tmp/.docker-cache            
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
      - run: cd /tmp/.docker-cache && ls && du -sh
#      - run: docker compose up -d --wait test-db

#      - run: |
#          rm -rf /tmp/.buildx-cache
#          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
