name: deploy

on:
  push:
    branches:
      #      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

#      - run: |
#          sudo mkdir -p ./.docker-cache/{image,overlay2}
#          sudo chown -R $USER:$USER ./.docker-cache
#          sudo chmod -R 777 ./.docker-cache

      - uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-docker-cache-${{ github.sha }}
          restore-keys: ${{ runner.os }}-docker-cache-
          path: |
            ./.docker-cache/image
            ./.docker-cache/overlay2

      - name: Stop Docker processes
        run: |
          sudo kill $(pidof dockerd) || true
          sudo kill $(pidof containerd) || true
          sleep 2

      - name: Configure Docker daemon
        run: |
          sudo mkdir -p /etc/docker
          sudo tee /etc/docker/daemon.json > /dev/null <<EOF
          {
            "data-root": "${{ github.workspace }}/.docker-cache",
            "storage-driver": "overlay2"
          }
          EOF

      - name: Start Docker daemon
        run: |
          sudo containerd &
          sleep 2
          sudo dockerd --debug &
          sleep 2
      - run: docker pull mysql:8.0.36
      - run: |
          docker images
          sudo chmod -R 777 ./.docker-cache
      #          sudo chown -R $USER:$USER ./.docker-cache


#          docker image

      #      - uses: docker/setup-buildx-action@v3


      #      - uses: docker/bake-action@v5
      #        with:
      ##          load: true
      #          set: |
      #            *.cache-from=type=local,src=/tmp/.docker-cache
      #            *.cache-to=type=local,dest=/tmp/.docker-cache-new,mode=max

      #      - run: docker compose up test

#      - run: docker compose build test
#      - run: |
#          rm -rf /tmp/.docker-cache
#          mv /tmp/.docker-cache-new /tmp/.docker-cache

