name: deploy

on:
  push:
    branches:
      #      - main

      - develop

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-docker-cache-${{ github.sha }}
          restore-keys: ${{ runner.os }}-docker-cache-
          path: ./docker.tar

      - name: Restore docker
        if: hashFiles('./docker.tar') != ''
        run: |
          sudo systemctl stop docker docker.socket
          sudo tar -xf ./docker.tar
          sudo rm -rf /var/lib/docker
          sudo mv var/lib/docker /var/lib/docker
          sudo systemctl start docker

      - name: Test
        run: docker compose up test --build

      - name: Build production server
        run: docker compose build server

      - name: Generate docker cache
        run: |
          docker compose down
          docker builder prune --force
          docker image prune --force --all
          sudo systemctl stop docker docker.socket
          sudo tar -cf ./docker.tar /var/lib/docker

