name: deploy

on:
  push:
    branches:
      #      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Stop Docker processes
        run: |
          sudo kill $(pidof dockerd) || true
          sudo kill $(pidof containerd) || true
          sleep 2

      - uses: actions/checkout@v4

      - run: sudo rm -rf /var/lib/docker/{image,overlay2}
      - run: mkdir -p /var/lib/docker/image
      - run: mkdir -p /var/lib/docker/overlay2

      - uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-docker-cache-${{ github.sha }}
          restore-keys: ${{ runner.os }}-docker-cache-
          path: |
            /var/lib/docker/image
            /var/lib/docker/overlay2

      - name: Start Docker daemon
        run: |
          sudo containerd &
          sleep 2
          sudo dockerd --debug &
          sleep 2

      - run: docker compose up -d test-db --wait

      - run: |
          docker images

      - name: Stop Docker processes
        run: |
          sudo kill $(pidof dockerd) || true
          sudo kill $(pidof containerd) || true
          sleep 2


#          sudo chmod -R 777 /tmp/.docker-cache

