name: deploy

on:
  push:
    branches:
      # - main
      - develop
#      - test

jobs:
  deploy:
    runs-on: ubuntu-24.04
    env:
      REGISTRY_ENDPOINT: ${{ secrets.REGISTRY_ENDPOINT }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-docker-cache-${{ github.sha }}
          restore-keys: ${{ runner.os }}-docker-cache-
          path: ./docker.tar

      - name: Restore docker cache
        if: hashFiles('./docker.tar') != ''
        run: |
          sudo systemctl stop docker docker.socket
          sudo rm -rf /var/lib/docker
          sudo tar -xf ./docker.tar -C /
          sudo systemctl start docker

      - name: Test
        run: |
          docker compose up test --build
          docker compose down

      - name: Login registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_ENDPOINT }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push production server
        run: docker compose build server --push

      - name: Generate docker cache
        run: |
          docker image prune --force
          docker builder prune --force
          sudo systemctl stop docker docker.socket
          sudo tar -cf ./docker.tar /var/lib/docker

